### ISSUE TITLE
Add managment system

### ISSUE THREAD

**Issue by Kobu** [ArjanCodes/discord-bot#2]
Implement a system with basic server managment functionalities:

- [x] Warn user
- [x] Mute User
- [x] Kick user
- [x] Ban user
- [x] Permaban user

**Comment by Kobu** [comment]
### Warn user
-  parameters 
    -  **user** : 
   user ID or
   mention of the user or
   user name
- usage
    - `/warn @BadUser`
    - `/warn 445004845948870` 
    - `/warn Kobu`
- effects
    - the warn command message gets autodeleted 
    - pings user and warns him about his behavior with a predefined message(s) 
    ```
    /warn @BadUser
    Bot: Hey @BadUser, be polite! 
    ```
___

### Mute user
-  parameters 
    -  **user** : 
   user ID,
   mention of the user,
   user name,
    -  **amount** (default = 1) : 
   number
    -  **unit** (default = "hour": 
   "minutes" or
   "hours" or
   "days"
    -  **reason**: 
   reason
- usage
    - `/mute @BadUser 20 minutes for being rude`
    - `/mute 445004845948870 1 hour` 
    - `/mute Kobu watch your profanity`
- effects
    -  the mute command message gets autodeleted 
    - mutes user for desired amount of time
    ```
    /mute @BadUser 20 minutes for being rude
    Bot: @BadUser got muted for {amount} {unit} for {reason}.
    ```
___

### Kick user
-  parameters 
    -  **user** : 
   user ID,
   mention of the user,
   user name,
    -  **reason** : 
   reason
- usage
    - `/kick @BadUser being rude`
    - `/kick 445004845948870 profanity` 
    - `/kick Kobu`
- effects
    - the kick command message gets autodeleted 
    - kicks the user from the server
    ```
    /kick @BadUser being rude
    Bot: @BadUser got kicked for {reason}.
    ```
___

### Ban user
-  parameters
    -  **user** : 
   user ID,
   mention of the user,
   user name,
    -  **reason** : 
   reason
    -  **amount** (default = 1) : 
   number
    -  **unit** (default = "hour": 
   "minutes" or
   "hours" or
   "days"
- usage
    - `/ban @BadUser 1 day spam`
    - `/ban 445004845948870` 
    - `/ban Kobu 20 hours rudeness`
- effects
    - the ban command message gets autodeleted 
    - bans the user from the server
    ```
    /ban @BadUser 1 day for spamming
    Bot: @BadUser got muted for {amount} {unit} for {reason}.
    ```
___

### Ban user
-  parameters
    -  **user** : 
   user ID,
   mention of the user,
   user name,
    -  **reason** (optional, ) : 
   reason

- usage
    - `/permaban @BadUser 1 day spam`
    - `/permaban 445004845948870` 
    - `/permaban Kobu 20 hours rudeness`
- effects
    - the permaban command message gets autodeleted 
    - permabans the user from the server
    ```
    /permaban @BadUser  spamming
    Bot: @BadUser got banned for {reason}.
    ```

**Comment by PedanticHacker** [comment]
Please see this link: https://discordhub.com/bot/commands

In there you'll find commands such as `!ban @user` which have the `!` as a command prefix and the `@` before the *user* parameter. I'd follow there format.

**Comment by Kobu** [comment]
Yes the @ before user parameter is allowed in every command as mentioned for example here 
- user :
   user ID,
   **mention of the user**,
   user name
- usage
   `/ban @BadUser`

It is the most reliable way of identifying a user.
As far as the command prefix goes it is still a subject to discussion. We can create a community poll in the discord server.
